// Patch node-pty gyp files to disable Spectre mitigation and fix
// missing winpty build scripts (git submodule not fully present)
const fs = require('fs');
const path = require('path');

const files = [
  path.join(__dirname, '..', 'node_modules', 'node-pty', 'binding.gyp'),
  path.join(__dirname, '..', 'node_modules', 'node-pty', 'deps', 'winpty', 'src', 'winpty.gyp'),
];

for (const file of files) {
  if (!fs.existsSync(file)) continue;
  let content = fs.readFileSync(file, 'utf8');
  let patched = false;
  if (content.includes("'SpectreMitigation': 'Spectre'")) {
    content = content.replace(/'SpectreMitigation': 'Spectre'/g, "'SpectreMitigation': 'false'");
    patched = true;
  }
  // Replace GetCommitHash.bat call with a static hash
  if (content.includes('GetCommitHash.bat')) {
    content = content.replace(/<!\(cmd \/c "cd shared && GetCommitHash\.bat"\)/g, '0000000000');
    patched = true;
  }
  // Replace UpdateGenVersion.bat call with the pre-created gen dir
  if (content.includes('UpdateGenVersion.bat')) {
    content = content.replace(/<!\(cmd \/c "cd shared && UpdateGenVersion\.bat <\(WINPTY_COMMIT_HASH\)"\)/g, 'gen');
    patched = true;
  }
  if (patched) {
    fs.writeFileSync(file, content);
    console.log(`Patched ${path.basename(file)}`);
  }
}

// Pre-create gen/GenVersion.h so the build doesn't need the bat scripts
const genDir = path.join(__dirname, '..', 'node_modules', 'node-pty', 'deps', 'winpty', 'src', 'gen');
if (!fs.existsSync(genDir)) fs.mkdirSync(genDir, { recursive: true });
const genHeader = path.join(genDir, 'GenVersion.h');
if (!fs.existsSync(genHeader)) {
  let version = '0.4.4-dev';
  try {
    const vFile = path.join(__dirname, '..', 'node_modules', 'node-pty', 'deps', 'winpty', 'VERSION.txt');
    if (fs.existsSync(vFile)) version = fs.readFileSync(vFile, 'utf8').trim();
  } catch {}
  fs.writeFileSync(genHeader,
    `// AUTO-GENERATED BY patch-spectre.js\n` +
    `const char GenVersion_Version[] = "${version}";\n` +
    `const char GenVersion_Commit[] = "0000000000";\n`
  );
  console.log('Created gen/GenVersion.h');
}
